name:                colorized-keys
version:             0.0
github:              karamellpelle/colorized-keys
license:             GPL-3
license-file:        COPYING
author:              karamellpelle@hotmail.com
maintainer:          karamellpelle@hotmail.com
copyright:           karamellpelle@hotmail.com

# FIXME: Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/karamellpelle/colorized-keys#readme>

language: GHC2021

extra-source-files:
- README.md
- CHANGELOG.md
data-dir:            .
data-files:
  - data-dir/colorized-keys/**/*
  - text/**/*
  - graphics/**/*

dependencies:
- base
- relude
- data-default
- microlens
- microlens-th
- microlens-mtl
- pandoc
- pandoc-types
- doctemplates
- file-io
- directory
- mtl
- aeson
- yaml
- attoparsec
- skylighting
#- os-string
#- HsYAML
#- libssh2
#- hashable
#- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wprepositive-qualified-module
- -Wno-name-shadowing
- -Wno-unused-top-binds
- -Wno-unused-matches
- -Wno-unused-imports

default-extensions:
 - NoImplicitPrelude
 - OverloadedStrings
 - GHC2021
 - LambdaCase
#   - ImportQualifiedPost
#   - TypeApplications
#   - RankNTypes
#   - ScopedTypeVariables
#   - FlexibleInstances
#   - GeneralizedNewtypeDeriving
#   - StandaloneDeriving


# private libraries (https://github.com/sol/hpack#library-fields)
library:
    source-dirs: source-lib
    # https://github.com/sol/hpack#handling-of-paths_-modules 
    when:
    - condition: false
      other-modules: Paths_colorized-keys 

## private libraries (https://github.com/sol/hpack#library-fields)
#internal-libraries:
#  colorized-keys-internal:
#      source-dirs: source-lib
#      # https://github.com/sol/hpack#handling-of-paths_-modules 
#      when:
#      - condition: false
#        other-modules: Paths_colorized-keys 
#
executables:
  #colorize-keys:
  #  main:                Main.hs
  #  source-dirs:         source-app
  #  generated-other-modules: 
  #      - Paths_colorized_keys
  #      - PackageInfo_colorized_keys
  #  ghc-options:
  #  - -threaded
  #  - -rtsopts
  #  - -with-rtsopts=-N
  #  dependencies:
  #  #- colorized-keys-internal
  #  - colorized-keys
  #  - filepath
  #  - gitrev

  colorized-filter:
    main: Main.hs
    source-dirs: source-filter
    generated-other-modules: 
        - Paths_colorized_keys
        - PackageInfo_colorized_keys
    ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
    dependencies:
        #- colorized-keys-internal
        - colorized-keys
        - filepath
        - gitrev


#tests:
#  colorized-keys-test:
#    main:                Spec.hs
#    source-dirs:         test/colorized-keys-test
#    # other-modules: <pull indidual files from project root>
#    dependencies:
#    #- colorized-keys-internal
#    - colorized-keys
#    - tasty
#    - tasty-hunit
#    - tasty-smallcheck
#    - smallcheck
#    - pretty-simple
#    ghc-options:
#      - -threaded
#      - -rtsopts
#      - -with-rtsopts=-N
